# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: abc609b081b7577c1063f70ffbdba321735f64024d10ddbcfecf1db2a84c4c863fe72225a600724b8df83fe57a91574548d514c35c9354004e0186720d52442a

test:
  secret_key_base: 77e70377990d3f88649334a277fe9797c85c61d1bce6052396e0681a8e7af6cedf66647cda5872e445eda76cae8e05c4ac6cb0f8e4f5ac3703f124166d7b823f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
